# -*- coding: utf-8 -*-
"""INFO450.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XDp8CED3c7xraB9bBM06mGF6MRbgzCtO

# Part 1 - Exploratory Data Analysis and Data Preparation
"""

import pandas as pd
import numpy as np

"""Imported all of the libraries and datasets

"""

df = pd.read_csv('IPUMS.csv')
OCC_df = pd.read_csv('OccupationCodes.csv')

"""converted csv to dataframes"""

df.head()

OCC_df.head()

OCC_df['OCC Code'].info()

df['OCC'].info()

"""Called both of the dataframes so we can see the all of the data and verify what needs to be cleaned. Verify what types of Dtype 'OCC' is in each of the df so we can convert them to match when we merge."""

df = df.dropna()

"""Use df.drop function to drop any invalid rows"""

df['OCC'] = df['OCC'].astype(str)
df = pd.merge(df, OCC_df, left_on='OCC', right_on='OCC Code', how='left')

"""set occ to a string then merged the data"""

df = df[(df['UHRSWORKT'] >= 30) & (df['UHRSWORKT'] <= 60)]
df = df[(df['INCWAGE'] >= 10000) & (df['INCWAGE'] <= 200000)]
df = df[df['WKSWORK1'] > 0]

"""Made three filters

1.   Filters employees who whos usual hours are at least 30 hours and no more than 60
2.   Filters employees whos income is at least 10,000 and nor more than 200000 dollars
3.   Filters employees to ensure that they all worked more than one week

"""

df = df.drop(columns=['Unnamed: 3', 'OCC Code'])
df = df.dropna(subset=['Occupation Title']) # Drop anyone whose job didn't merge

"""Removed unnamed:3 because it was completely empty, dropped occ code since we already had one from the original IPUMS.csv.

Removed "noise variables"
"""

median_income = df['INCWAGE'].median()
df['HighEarner'] = (df['INCWAGE'] > median_income).astype(int)
df["HourlyEfficiency"] = df["INCWAGE"] / (df["WKSWORK1"] * df["UHRSWORKT"])
df["EdWorkIntensity"] = df["EDUC"] * df["UHRSWORKT"]

avg_inc_by_occupation = df.groupby('Occupation Title')['INCWAGE'].mean().reset_index()
avg_wage_by_education = df.groupby('EDUC')['INCWAGE'].mean().reset_index()
avg_hours_by_occupation = df.groupby('Occupation Title')['UHRSWORKT'].mean().reset_index()

df

"""EDA



"""

import plotly.express as px

# 1. Define the list of the 8 real, valid job sectors
valid_sectors = [
    'Management Business and Financial',
    'Sales and Office',
    'Service Occupations',
    'Production Transportation and Material Moving',
    'Education Legal Arts and Media',
    'Natural Resources Construction and Maintenance',
    'Computer Engineering and Science',
    'Healthcare Practitioners and Technical'
]

# 2. Filter your main dataframe to ONLY keep rows that match the valid sectors
df = df[df['Major Category'].isin(valid_sectors)]

horizontal_bar_chart = px.bar(df['Major Category'].value_counts().reset_index(),
                    x='count',
                    y='Major Category',
                    orientation='h',
                    title='Workforce Distribution: Number of Employees per Sector',
                    labels={'count': 'Number of Employees', 'Major Category': 'Job Sector'},
                    color='Major Category')
horizontal_bar_chart.update_layout(showlegend=False)
horizontal_bar_chart.show()

"""Created a horizontal bar for vis 1. Imported plotly instead of matplot lib since it is interactive. Px.bar to pull the bar chart and used the .value_counts().reset_index() functions to calculate the exact number of employees within each major category. Labeled the axis accordingly with job sector and number of employees. horizontal_bar_chart.update_layout(showlegend=False) gets rid of the legend on the right, the legend was redundant."""

histogram = px.histogram(df,
                    x='UHRSWORKT',
                    title='Workplace Culture: Distribution of Weekly Hours Worked',
                    labels={'UHRSWORKT': 'Hours Worked Per Week', 'count': 'Number of Employees', 'y': 'Number of Employees'},
                    color_discrete_sequence=['#1f77b4'])
histogram.update_layout(yaxis_title="Number of Employees")
histogram.show()

"""Used px.historgram to show how many hours people actually work per week. Unlike the first vis we did, I let plotly automatically count and group the raw data. I used the labels parameter as a translator to turn the code names, like UHRSWORKT, so that the user can read it as Hours Worked Per Week. Had to update the y axis since plotly couldn't translate it from the dictionary."""

sector_boxplot = px.box(df,
                 x='Major Category',
                 y='INCWAGE',
                 title='Income Distribution by Job Sector',
                 labels={'Major Category': 'Job Sector', 'INCWAGE': 'Annual Income ($)'},
                 color='Major Category')
sector_boxplot.update_layout(showlegend=False)
sector_boxplot

"""This box plot visualizes the spread of annual income across broad job sectors. Using px.box() function, we map the "Major Category" job sectors to the x and the "INCWAGE" annual income to the y. The layout is updated using update_layout() to hide the redundant color legend. Using this visualization, we can  observe which sector has the highest median salary and which sectors have the longest "whiskers" and highest outliers—indicating fields with the greatest potential for massive financial upside versus fields with highly standardized, tight wage brackets.

The outliers in these charts highlight salaries that are unusually high compared to the standard baseline of that specific industry, rather than the overall workforce. Consequently, sectors with tightly standardized average wages (like Healthcare or Sales) flag their top earners as extreme outliers, whereas sectors with highly variable base pay (like Tech or Management) absorb those large salaries into their 'normal' expected range.
"""

import plotly.express as px

# 1. Aggregate the data: Calculate average income, average hours, and total employee count per sector
sector_summary = df.groupby('Major Category').agg(
    Avg_Income=('INCWAGE', 'mean'),
    Avg_Hours=('UHRSWORKT', 'mean'),
    Employee_Count=('INCWAGE', 'count')
).reset_index()

tradeoff_scatter = px.scatter(sector_summary,
                 x='Avg_Hours',
                 y='Avg_Income',
                 size='Employee_Count', # Makes the bubble bigger if more people work in that sector
                 color='Major Category',
                 hover_name='Major Category',
                 title='The Time-Money Tradeoff: Average Income vs. Hours Worked by Sector',
                 labels={'Avg_Hours': 'Average Weekly Hours', 'Avg_Income': 'Average Annual Income ($)'},
                 size_max=40) # Caps the maximum bubble size so they don't overlap too much

tradeoff_scatter.update_layout(showlegend=False)

tradeoff_scatter.update_layout(
    yaxis_title="Number of Employees",
    xaxis=dict(range=[38, 44])
)

tradeoff_scatter.show()

"""By mapping Average Weekly Hours against Average Annual Income (with bubble size showing workforce volume), this chart reveals the return on time invested across career paths. We can quickly identify:

High-Efficiency Sectors: Careers offering high wages without exceeding the standard 40-hour work week.

Low-Efficiency Sectors: Careers demanding longer hours for lower financial
returns.

# Part 2 - Inferential Statistics
"""

import pandas as pd
import numpy as np
from scipy import stats
import math

print(df[['INCWAGE', 'SEX']].describe())
print("Unique SEX values:", df['SEX'].unique())

df = df[(df['INCWAGE'] > 0) & (df['SEX'].isin([1, 2]))]

# 95% Confidence Interval
income = df['INCWAGE']

n = len(income)
mean_income = income.mean()
std_income = income.std()

# standard error
se = std_income / math.sqrt(n)

# the t-value for 95%
t_value = stats.t.ppf(0.975, n-1)

lower = mean_income - t_value * se
upper = mean_income + t_value * se

print("\nConfidence Interval")
print("Mean:", round(mean_income, 2))
print("Lower:", round(lower, 2))
print("Upper:", round(upper, 2))

# comparing the groups
male = df[df['SEX'] == 1]['INCWAGE']
female = df[df['SEX'] == 2]['INCWAGE']

print("\nGroup Means")
print("Male:", round(male.mean(), 2))
print("Female:", round(female.mean(), 2))

# two-sample t-test
t_stat, p_val = stats.ttest_ind(male, female, equal_var=False)

print("\nT-Test Results")
print("t-stat:", round(t_stat, 3))
print("p-value:", round(p_val, 6))

# conclusion
if p_val < 0.05:
    print("\nConclusion: Significant difference between groups")
else:
    print("\nConclusion: No significant difference")

"""The 95% confidence interval shows the range where the true average income is likely to fall. This is useful because it gives more information than just a single mean value.


When comparing the two groups, males had a higher average income than females. However, to determine whether this difference is meaningful, a statistical test was required. The two sample t-tests produced a p-value less than 0.05. This means the difference in average income between males and females is statistically significant.

In simple terms, this suggests that the difference in income between the two groups is unlikely to be due to random chance alone. This is important for the project because it shows that income varies across groups in a measurable and statistically supported way. However, this test does not explain why the difference exists. Other factors such as education, occupation, and work hours may also influence income.

# Part 3 - Predictive Modeling
"""

model_df = df
model_df['HighEarner'] = df['HighEarner']
model_df.head()

model_df['HighEarner'].value_counts()

from sklearn.model_selection import train_test_split

X = model_df[[
    "AGE",
    "SEX",
    "RACE",
    "MARST",
    "OCC",
    "IND",
    "CLASSWKR",
    "EDUC",
    "UHRSWORKT",
    "WKSWORK1",
    "EdWorkIntensity"
]]
y = model_df["HighEarner"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

numeric_features = ["AGE", "UHRSWORKT", "WKSWORK1", "EdWorkIntensity"]
categorical_features = [
    "SEX",
    "RACE",
    "MARST",
    "OCC",
    "IND",
    "CLASSWKR",
    "EDUC"
]

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
preprocess = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"),categorical_features)
    ],
    remainder='passthrough'
)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier

model = Pipeline([
    ("prep", preprocess),
    ("clf",DecisionTreeClassifier(max_depth=10,min_samples_leaf=20))
])

model.fit(X_train,y_train)

from sklearn.tree import export_graphviz
import graphviz

tree = model.named_steps["clf"]
feature_names = model.named_steps["prep"].get_feature_names_out()

dot = export_graphviz(
    tree,
    out_file=None,
    feature_names=feature_names,
    class_names=["Low", "High"],
    filled=True,
    rounded=True,
    special_characters=True,
    max_depth=4
)

graphviz.Source(dot)

y_pred=model.predict(X_test)
y_pred

from sklearn.metrics import confusion_matrix, precision_score, accuracy_score,recall_score

print(confusion_matrix(y_test,y_pred))
print("accuracy", accuracy_score(y_test,y_pred))
print("precision", precision_score(y_test,y_pred))
print("recall",recall_score(y_test,y_pred))

"""We have a moderate level of trust in our model, as its performance is fairly consistent across accuracy, precision, and recall. The confusion matrix shows errors are relatively balanced, indicating no strong bias toward a single class. However, overall performance is still moderate, and since decision trees can overfit, the model may struggle to generalize to new data. Overall, the model is resonably reliable but could benefit from further improvement.

# Part 4 - Streamlit App
"""

import streamlit as st
import pandas as pd
import plotly.express as px
# Login with GitHub account here= streamlit.io
# All files & App are uploaded (as of 7pm April 16 2026)


st.title("Workforce Dashboard")

# Bar chart sample
horizontal_bar_chart = px.bar(df['Major Category'].value_counts().reset_index(),
                    x='count',
                    y='Major Category',
                    orientation='h',
                    title='Workforce Distribution: Number of Employees per Sector',
                    labels={'count': 'Number of Employees', 'Major Category': 'Job Sector'},
                    color='Major Category')
horizontal_bar_chart.update_layout(showlegend=False)
horizontal_bar_chart.show()

st.plotly_chart(horizontal_bar_chart)

# Histogram sample
histogram = px.histogram(df,
                    x='UHRSWORKT',
                    title='Workplace Culture: Distribution of Weekly Hours Worked',
                    labels={'UHRSWORKT': 'Hours Worked Per Week', 'count': 'Number of Employees', 'y': 'Number of Employees'},
                    color_discrete_sequence=['#1f77b4'])
histogram.update_layout(yaxis_title="Number of Employees")
histogram.show()

st.plotly_chart(histogram)
st.dataframe(df)
